# Site settings
title: merikonjatta
email: merikonjatta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Japanese web developer Shinya Maeyama.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://merikonjatta.com" # the base hostname & protocol for your site
twitter_username:  merikonjatta
github_username:   merikonjatta
facebook_username: merikonjatta
timezone: Asia/Tokyo
permalink: /writeups/:year/:month/:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  coderay_css: class
  coderay_line_numbers: nil
